### ISSUE TITLE
网关为192.168.2.1 报错14200

### ISSUE THREAD

**Issue by niziming** [klren0312/RubbingNetNotice#1]
(node:14200) UnhandledPromiseRejectionWarning: ReferenceError: error is not defined
    at axios.get.then.catch.err (D:\WebstormProjects\RubbingNetNotice\index.js:38:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:14200) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not
 handled with .catch(). (rejection id: 5)
{ Error: Request failed with status code 404
    at createError (D:\WebstormProjects\RubbingNetNotice\node_modules\axios\lib\core\createError.js:16:15)
    at settle (D:\WebstormProjects\RubbingNetNotice\node_modules\axios\lib\core\settle.js:18:12)
    at IncomingMessage.handleStreamEnd (D:\WebstormProjects\RubbingNetNotice\node_modules\axios\lib\adapters\http.js:202:11)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by niziming** [comment]
![TIM截图20190823100635](https://user-images.githubusercontent.com/22069750/63561777-b89f0280-c58d-11e9-94ad-609c661f6d8a.png)

**Comment by klren0312** [comment]
你是斐讯 我这个是针对腾达写的
两个厂商不一样, 接口也会不一样 查看下斐讯的接口 把代码改改看
